POST http://127.0.0.1:8000/add_to_favorite/
Content-Type: application/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{"item_id": "6"}

###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{"username": "user1", "password": "user1pw", "email": "user1@gmail.com"}

###
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{"username": "admin1", "password": "shopmoreadmin1pw"}

###
GET http://127.0.0.1:8000/test_view/

###
POST http://127.0.0.1:8000/user/
Content-Type: application/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{}
###
POST http://127.0.0.1:8000/user/edit_info/
Content-Type: application/json
Authorization: Token 14525311f571f37e935bb27a1d3db4143e5dd78d

{"password": "TonyTony@gmail.com"}

###
POST http://127.0.0.1:8000/product/recommendation/
Content-Type: application/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{}

###
GET http://127.0.0.1:8000/Admin/item/display/
Content-Type: applicatiion/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{}
###

POST http://127.0.0.1:8000/Admin/item/add/
Content-Type: application/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{"name": "Glass Bottle", "description": "Unique Shape", "category": "2", "image": "bottle.jpg", "price": "20", "quantity": "70", "status": "1"}

###
PUT http://127.0.0.1:8000/Admin/item/edit/10/
Content-Type: application/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{"itemName": "Glass Bottle", "itemDescription": "High temperature resistance", "itemCategory": "3", "itemImage": "bottle.jpg", "itemPrice": "20", "itemQuantity": "65", "itemStatus": "1"}
###
DELETE  http://127.0.0.1:8000/Admin/item/delete/10/
Content-Type: application/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{}
###
GET http://127.0.0.1:8000/Admin/user/display/
Content-Type: applicatiion/json
Authorization: Token b09782e294306013522c0610bbbe5e601e021b3b

{}
###
POST  http://127.0.0.1:8000/Admin/user/add/
Content-Type: application/json
Authorization: Token b09782e294306013522c0610bbbe5e601e021b3b

{"username": "August", "accountType": "1", "password": "Augustpw", "email": "August@gmail.com", "profilePhoto": "august.jpg", "address": "cuhk uc"}

###
POST  http://127.0.0.1:8000/Admin/user/edit/9/
Content-Type: application/json
Authorization: Token b09782e294306013522c0610bbbe5e601e021b3b

{"username": "August", "accountType": "0", "password": "Augustpw", "email": "August1@gmail.com", "profilePhoto": "august.jpg", "address": "cuhk wys"}

###
DELETE   http://127.0.0.1:8000/Admin/user/delete/9/
Content-Type: application/json
Authorization: Token b09782e294306013522c0610bbbe5e601e021b3b

{}