POST http://127.0.0.1:8000/add_to_favorite/
Content-Type: application/json
Authorization: Token 00369113d57b2220c7cd039caa00126b0043a4ab

{"item_id": "7"}

###
GET http://127.0.0.1:8000/display_favorite/
Content-Type: application/json
Authorization: Token 00369113d57b2220c7cd039caa00126b0043a4ab

{}

###
DELETE  http://127.0.0.1:8000/delete_favorite/6/
Content-Type: application/json
Authorization: Token 00369113d57b2220c7cd039caa00126b0043a4ab

{}
###
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{"username": "July", "password": "Julypw", "email": "July@gmail.com"}

###
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{"username": "John123", "password": "John123pw"}

###
GET http://127.0.0.1:8000/test_view/

###
POST http://127.0.0.1:8000/user/
Content-Type: application/json
Authorization: Token ccc016a5bdfe22ccd8c07139ec00c1cd298311d3

{"userID": "13"}
###
POST http://127.0.0.1:8000/user/edit_info/
Content-Type: application/json
Authorization: Token 13c32dc64d23ad8f6f13248c5c487494bbe1a74d

{"phoneNo": ""}

###
POST http://127.0.0.1:8000/product/recommendation/
Content-Type: application/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{}

###
GET http://127.0.0.1:8000/Admin/item/display/
Content-Type: applicatiion/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{}
###

POST http://127.0.0.1:8000/Admin/item/add/
Content-Type: application/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{"name": "Glass Bottle", "description": "Unique Shape", "category": "2", "image": "bottle.jpg", "price": "20", "quantity": "70", "status": "1"}

###
POST http://127.0.0.1:8000/Admin/item/edit/10/
Content-Type: application/json
Authorization: Token b09782e294306013522c0610bbbe5e601e021b3b

{"itemName": "Glass Bottle", "itemDescription": "High temperature resistance", "itemCategory": "Kitchen Electronics,Campaign", "itemImage": "bottle.jpg", "itemPrice": "20", "itemQuantity": "65", "itemStatus": "1"}
###
DELETE  http://127.0.0.1:8000/Admin/item/delete/10/
Content-Type: application/json
Authorization: Token d5219af605fe3da8ce570d8422e11f5e8090c4e7

{}
###
GET http://127.0.0.1:8000/Admin/user/display/
Content-Type: applicatiion/json
Authorization: Token b09782e294306013522c0610bbbe5e601e021b3b

{}
###
POST  http://127.0.0.1:8000/Admin/user/add/
Content-Type: application/json
Authorization: Token b09782e294306013522c0610bbbe5e601e021b3b

{"username": "August", "accountType": "1", "password": "Augustpw", "email": "August@gmail.com", "profilePhoto": "august.jpg", "address": "cuhk uc"}

###
POST  http://127.0.0.1:8000/Admin/user/edit/8/
Content-Type: application/json
Authorization: Token b09782e294306013522c0610bbbe5e601e021b3b

{"username": "Tony", "accountType": "0", "password": "Tonypw", "email": "TonyTony@gmail.com", "profilePhoto": "tony.jpg", "address": "cuhk wys", "phoneNo": ""}

###
DELETE   http://127.0.0.1:8000/Admin/user/delete/9/
Content-Type: application/json
Authorization: Token b09782e294306013522c0610bbbe5e601e021b3b

{}